name: Build crDroid A51 on Crave

on:
  workflow_dispatch:

jobs:
  crave-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Crave CLI
        run: |
          mkdir -p ~/.bin
          curl -sL https://raw.githubusercontent.com/accupara/crave/main/get_crave.sh | bash
          sudo mv crave /usr/local/bin/crave
          chmod +x /usr/local/bin/crave

      - name: Configure Crave Auth & Link Project
        run: |
          echo "${{ secrets.CRAVE_CONF }}" > $HOME/crave.conf
          git init
          git remote add origin https://github.com/accupara/los23.2.git

      - name: Trigger Crave Cloud Build
        run: |
          crave run --no-patch -- "rm -rf .repo/local_manifests && repo init -u https://github.com/crdroidandroid/android.git -b 17.0 --git-lfs && git clone https://github.com/Exynos9611Development/local_manifests.git -b lineage-23.2 .repo/local_manifests && /opt/crave/resync.sh && source build/envsetup.sh && lunch crdroid_a51-userdebug && mka bacon"
